/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_singun_wrapper_WebRTC_GainControl */

#ifndef _Included_com_singun_wrapper_WebRTC_GainControl
#define _Included_com_singun_wrapper_WebRTC_GainControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_singun_wrapper_WebRTC_GainControl
 * Method:    initGainControl
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_singun_wrapper_WebRTC_GainControl_initGainControl
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_singun_wrapper_WebRTC_GainControl
 * Method:    processGainControl
 * Signature: (I[SI)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_singun_wrapper_WebRTC_GainControl_processGainControl
  (JNIEnv *, jobject, jint, jshortArray, jint);

/*
 * Class:     com_singun_wrapper_WebRTC_GainControl
 * Method:    releaseGainControl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_singun_wrapper_WebRTC_GainControl_releaseGainControl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
