/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_singun_wrapper_WebRTC_EchoCancel */

#ifndef _Included_com_singun_wrapper_WebRTC_EchoCancel
#define _Included_com_singun_wrapper_WebRTC_EchoCancel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_singun_wrapper_WebRTC_EchoCancel
 * Method:    initEchoCancel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_singun_wrapper_WebRTC_EchoCancel_initEchoCancel
(JNIEnv *env, jobject obj, jint samp_freq);

/*
 * Class:     com_singun_wrapper_WebRTC_EchoCancel
 * Method:    processEchoCancel
 * Signature: (I[S[SI)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_singun_wrapper_WebRTC_EchoCancel_processEchoCancel
  (JNIEnv *, jobject, jint, jshortArray, jshortArray, jint);

/*
 * Class:     com_singun_wrapper_WebRTC_EchoCancel
 * Method:    releaseEchoCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_singun_wrapper_WebRTC_EchoCancel_releaseEchoCancel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
