/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_singun_wrapper_WebRTC_WebRTCWrapper */

#ifndef _Included_com_singun_wrapper_WebRTC_WebRTCWrapper
#define _Included_com_singun_wrapper_WebRTC_WebRTCWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_singun_wrapper_WebRTC_NoiseSuppress
 * Method:    initNoiseSuppress
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_singun_wrapper_WebRTC_NoiseSuppress_initNoiseSuppress
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_singun_wrapper_WebRTC_NoiseSuppress
 * Method:    processNoiseSuppress
 * Signature: ([S)Z
 */
JNIEXPORT jboolean JNICALL Java_com_singun_wrapper_WebRTC_NoiseSuppress_processNoiseSuppress
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_singun_wrapper_WebRTC_NoiseSuppress
 * Method:    releaseNoiseSuppress
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_singun_wrapper_WebRTC_NoiseSuppress_releaseNoiseSuppress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
