/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_singun_wrapper_WebRTC_WebRTCWrapper */

#ifndef _Included_com_singun_wrapper_WebRTC_WebRTCWrapper
#define _Included_com_singun_wrapper_WebRTC_WebRTCWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_singun_wrapper_WebRTC_WebRTCWrapper
 * Method:    init
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_singun_wrapper_WebRTC_WebRTCWrapper_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_singun_wrapper_WebRTC_WebRTCWrapper
 * Method:    processNoise
 * Signature: ([S)Z
 */
JNIEXPORT jboolean JNICALL Java_com_singun_wrapper_WebRTC_WebRTCWrapper_processNoise
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_singun_wrapper_WebRTC_WebRTCWrapper
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_singun_wrapper_WebRTC_WebRTCWrapper_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
